name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install CDK
      run: npm install -g aws-cdk

    - name: Install dependencies
      run: npm install
      working-directory: ./cdk

    - name: Build Go Lambda
      run: |
        cd cdk/hello-world
        GOOS=linux go build -o hello-world main.go
        cd ../..

    - name: Deploy CDK
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: cdk deploy --require-approval never
      working-directory: ./cdk
